language: node_js

node_js:
  - "10"
  - "12"
  - "14"

install:
  - make install
  - npm install codecov nyc -g

before_script:
  - make lint
  - make build

script:
  - make cov

after_success:
  - codecov -f ./coverage/coverage-final.json
