/**
 * @author WMXPY
 * @namespace Magic
 * @description Port
 */

export enum PORT_NUMBER {

    DNS_SERVICE_PORT = 53,
    FTP_PORT = 20,
    FTP_CC_PORT = 21,
    HTTP_PORT = 80,
    HTTPS_PORT = 443,
    INTERNET_MESSAGE_ACCESS_PROTOCOL_PORT = 143,
    INTERNET_RELAY_CHAT_PORT = 194,
    MONGODB_DEFAULT_PORT = 27017,
    MY_SQL_DEFAULT_PORT = 3306,
    NETWORK_NEWS_TRANSFER_PROTOCOL_PORT = 119,
    NETWORK_TIME_PROTOCOL_PORT = 123,
    POST_OFFICE_PROTOCOL_PORT = 110,
    POSTGRE_SQL_DEFAULT_PORT = 5432,
    REDIS_DEFAULT_PORT = 6379,
    SIMPLE_MAIL_TRANSFER_PROTOCOL_PORT = 25,
    SIMPLE_NETWORK_MANAGEMENT_PROTOCOL_PORT = 161,
    SQL_SERVER_DEFAULT_PORT = 1433,
    SSH_PORT = 22,
    TELNET_PORT = 23,
}
