/**
 * @author WMXPY
 * @namespace Magic
 * @description Time
 */

export enum TIME_CHANGE {

    SECOND_TO_HALF_MINUTE = 30,
    SECOND_TO_MINUTE = 60,
    MINUTE_TO_QUARTER_HOUR = 15,
    MINUTE_TO_HALF_HOUR = 30,
    MINUTE_TO_HOUR = 60,
    HOUR_TO_DAY = 24,
    DAY_TO_WEEK = 7,
    DAY_TO_MONTH = 30,
    DAY_TO_YEAR = 365,
    MONTH_TO_QUARTER = 4,
    YEAR_TO_DECADE = 10,
}

export enum TIME_IN_DAYS {

    DAY = 1,

    WEEK = TIME_IN_DAYS.DAY * TIME_CHANGE.DAY_TO_WEEK,
    TWO_WEEKS = TIME_IN_DAYS.WEEK * 2,

    MONTH = TIME_IN_DAYS.DAY * TIME_CHANGE.DAY_TO_MONTH,
    TWO_MONTHS = TIME_IN_DAYS.MONTH * 2,
    QUARTER = TIME_IN_DAYS.MONTH * TIME_CHANGE.MONTH_TO_QUARTER,

    YEAR = TIME_IN_DAYS.DAY * TIME_CHANGE.DAY_TO_YEAR,
    DECADE = TIME_IN_DAYS.YEAR * TIME_CHANGE.YEAR_TO_DECADE,
}

export enum TIME_IN_SECONDS {

    SECOND = 1,
    HALF_MINUTE = TIME_IN_SECONDS.SECOND * TIME_CHANGE.SECOND_TO_HALF_MINUTE,
    MINUTE = TIME_IN_SECONDS.SECOND * TIME_CHANGE.SECOND_TO_MINUTE,

    QUARTER_HOUR = TIME_IN_SECONDS.MINUTE * TIME_CHANGE.MINUTE_TO_QUARTER_HOUR,
    HALF_HOUR = TIME_IN_SECONDS.MINUTE * TIME_CHANGE.MINUTE_TO_HALF_HOUR,
    HOUR = TIME_IN_SECONDS.MINUTE * TIME_CHANGE.MINUTE_TO_HOUR,

    DAY = TIME_IN_SECONDS.HOUR * TIME_CHANGE.HOUR_TO_DAY,
    WEEK = TIME_IN_SECONDS.DAY * TIME_CHANGE.DAY_TO_WEEK,
    TWO_WEEKS = TIME_IN_SECONDS.WEEK * 2,

    MONTH = TIME_IN_SECONDS.DAY * TIME_CHANGE.DAY_TO_MONTH,
    TWO_MONTHS = TIME_IN_SECONDS.MONTH * 2,
    QUARTER = TIME_IN_SECONDS.MONTH * TIME_CHANGE.MONTH_TO_QUARTER,

    YEAR = TIME_IN_SECONDS.DAY * TIME_CHANGE.DAY_TO_YEAR,
    DECADE = TIME_IN_SECONDS.YEAR * TIME_CHANGE.YEAR_TO_DECADE,
}

export enum TIME_IN_MILLISECONDS {

    SECOND = 1000,
    HALF_MINUTE = TIME_IN_MILLISECONDS.SECOND * TIME_CHANGE.SECOND_TO_HALF_MINUTE,
    MINUTE = TIME_IN_MILLISECONDS.SECOND * TIME_CHANGE.SECOND_TO_MINUTE,

    QUARTER_HOUR = TIME_IN_MILLISECONDS.MINUTE * TIME_CHANGE.MINUTE_TO_QUARTER_HOUR,
    HALF_HOUR = TIME_IN_MILLISECONDS.MINUTE * TIME_CHANGE.MINUTE_TO_HALF_HOUR,
    HOUR = TIME_IN_MILLISECONDS.MINUTE * TIME_CHANGE.MINUTE_TO_HOUR,

    DAY = TIME_IN_MILLISECONDS.HOUR * TIME_CHANGE.HOUR_TO_DAY,
    WEEK = TIME_IN_MILLISECONDS.DAY * TIME_CHANGE.DAY_TO_WEEK,
    TWO_WEEKS = TIME_IN_MILLISECONDS.WEEK * 2,

    MONTH = TIME_IN_MILLISECONDS.DAY * TIME_CHANGE.DAY_TO_MONTH,
    TWO_MONTHS = TIME_IN_MILLISECONDS.MONTH * 2,
    QUARTER = TIME_IN_MILLISECONDS.MONTH * TIME_CHANGE.MONTH_TO_QUARTER,

    YEAR = TIME_IN_MILLISECONDS.DAY * TIME_CHANGE.DAY_TO_YEAR,
    DECADE = TIME_IN_MILLISECONDS.YEAR * TIME_CHANGE.YEAR_TO_DECADE,
}
