/**
 * @author WMXPY
 * @namespace Magic
 * @description Time
 */

export enum TIME_CHANGE {

    SECOND_TO_MINUTE = 60,
    MINUTE_TO_HOUR = 60,
    HOUR_TO_DAY = 24,
    DAY_TO_WEEK = 7,
}

export enum TIME_IN_MILLISECONDS {

    SECOND = 1000,
    MINUTE = TIME_IN_MILLISECONDS.SECOND * TIME_CHANGE.SECOND_TO_MINUTE,
    HOUR = TIME_IN_MILLISECONDS.MINUTE * TIME_CHANGE.MINUTE_TO_HOUR,
    DAY = TIME_IN_MILLISECONDS.HOUR * TIME_CHANGE.HOUR_TO_DAY,
    WEEK = TIME_IN_MILLISECONDS.DAY * TIME_CHANGE.DAY_TO_WEEK,
}
